// src/data/booksData.ts
import { Book } from "./Book";

export const initialBooks: Book[] = [
  {
    id: 1,
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    genre: "Công nghệ",
    publishedYear: 2008,
    quantity: 20,
    available: 15,
    isbn: "978-0132350884",
    status: "available",
  },
  {
    id: 2,
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    genre: "Tâm lý học",
    publishedYear: 1936,
    quantity: 20,
    available: 0,
    isbn: "978-6049225326",
    status: "out_of_stock",
  },
  {
    id: 3,
    title: "Tôi tài giỏi, bạn cũng thế",
    author: "Adam Khoo",
    genre: "Phát triển bản thân",
    publishedYear: 2005,
    quantity: 8,
    available: 8,
    isbn: "978-9814181447",
    status: "available",
  },
  {
    id: 4,
    title: "Nhà giả kim",
    author: "Paulo Coelho",
    genre: "Tiểu thuyết",
    publishedYear: 1988,
    quantity: 10,
    available: 10,
    isbn: "978-0061122415",
    status: "available",
  },
  {
    id: 5,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    genre: "Công nghệ",
    publishedYear: 1999,
    quantity: 12,
    available: 5,
    isbn: "978-0201616224",
    status: "available",
  },
  {
    id: 6,
    title: "Refactoring: Improving the Design of Existing Code",
    author: "Martin Fowler",
    genre: "Công nghệ",
    publishedYear: 1999,
    quantity: 7,
    available: 2,
    isbn: "978-0201485677",
    status: "available",
  },
  {
    id: 7,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Phát triển bản thân",
    publishedYear: 2018,
    quantity: 30,
    available: 30,
    isbn: "978-0735211292",
    status: "available",
  },
  {
    id: 8,
    title: "Tâm lý học về tiền",
    author: "Morgan Housel",
    genre: "Tâm lý học",
    publishedYear: 2020,
    quantity: 25,
    available: 9,
    isbn: "978-0857197689",
    status: "available",
  },
  {
    id: 9,
    title: "Dune",
    author: "Frank Herbert",
    genre: "Tiểu thuyết",
    publishedYear: 1965,
    quantity: 6,
    available: 0,
    isbn: "978-0441172719",
    status: "out_of_stock",
  },
  {
    id: 10,
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    genre: "Công nghệ",
    publishedYear: 1994,
    quantity: 5,
    available: 1,
    isbn: "978-0201633610",
    status: "available",
  },
  {
    id: 11,
    title: "Deep Work",
    author: "Cal Newport",
    genre: "Phát triển bản thân",
    publishedYear: 2016,
    quantity: 12,
    available: 12,
    isbn: "978-1455586691",
    status: "available",
  },
  {
    id: 12,
    title: "Head First Java (2nd Edition)",
    author: "Kathy Sierra, Bert Bates",
    genre: "Công nghệ",
    publishedYear: 2005,
    quantity: 0,
    available: 0,
    isbn: "978-0596009205",
    status: "discontinued",
  },
];

// (tuỳ chọn) danh sách thể loại để dùng cho bộ lọc/dropdown
export const genres = [
  "Công nghệ",
  "Phát triển bản thân",
  "Tiểu thuyết",
  "Tâm lý học",
];
